name: Generate RSS

on:
  schedule:
    - cron: '0 */4 * * *'  # every 4 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Generate RSS
        run: python generate_rss.py

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/feed.xml
          if [ -f docs/email.html ]; then git add docs/email.html; fi
          if ! git diff --cached --quiet; then
            git commit -m "Update RSS feed and HTML"
            git push
          else
            echo "No changes to commit"
          fi


